parameters:
#    class_central_scraper.example.class: ClassCentral\ScraperBundle\Example

services:
#    class_central_scraper.example:
#        class: %class_central_scraper.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
