<?php

namespace ClassCentral\SiteBundle\Command;

use ClassCentral\SiteBundle\Entity\Offering;
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class GenerateExcelCommand extends ContainerAwareCommand {

    const  TITLE_ROW = 3;

    protected function configure()
    {
        $this
            ->setName("classcentral:generateexcel")
            ->setDescription("Generates an excel file containing a list of all courses");
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        // Initialization
        $em = $this->getContainer()->get('doctrine')->getManager();
        $phpExcel = $this->getPHPExcel();
        $now = new \DateTime();

        // Get all the offerings
        $allOfferings = $em->getRepository("ClassCentralSiteBundle:Offering")->findAllByInitiative();
        $activeSheetNumber = 0;
        foreach(Offering::$types as $typeKey => $type)
        {

            $offerings = $allOfferings[$typeKey];
            $activeSheet = $phpExcel->createSheet($activeSheetNumber++);
            $activeSheet->setTitle($typeKey);
            $activeSheet->setCellValue('A1',$type['desc'] . ' courses - generated on ' . $now->format("jS M, Y") .' by Class Central www.class-central.com');

            // Set the row titles
            $row = self::TITLE_ROW; $column = 0;
            $activeSheet->setCellValueByColumnAndRow($column++,$row,"Course Name");
            $activeSheet->setCellValueByColumnAndRow($column++,$row, "Length");
            $activeSheet->setCellValueByColumnAndRow($column++,$row, "Start Date");
            $activeSheet->setCellValueByColumnAndRow($column++,$row, "Stream");
            $activeSheet->setCellValueByColumnAndRow($column++,$row, "Initiative");
            $activeSheet->setCellValueByColumnAndRow($column++,$row, "Institution(s)");
            $activeSheet->setCellValueByColumnAndRow($column++,$row, "Instructor(s)");

            $row++;
            foreach($offerings as $offering)
            {
               $this->setOfferingRow($activeSheet,$offering,$row++);
            }


            // Make the worksheet prettier
            $titleRow = self::TITLE_ROW;
            // Special case for  course name row
            $activeSheet->getColumnDimension('A')->setWidth(50);
            $activeSheet->getStyle('A' .$titleRow)->getFont()->setBold(true);
            // Set Auto column width
            for( $i = 'B'; $i <= 'H'; $i++ )
            {
                $activeSheet->getColumnDimension($i)->setAutoSize(true);
                $activeSheet->getStyle($i .$titleRow)->getFont()->setBold(true);
            }

        }

        $phpExcel->setActiveSheetIndex(0); // Reset the active sheet to the first sheet
        $objWriter = \PHPExcel_IOFactory::createWriter($phpExcel,'Excel2007');
        $objWriter->save("extras/moocs.xslx");

    }

    /**
     * Initializes the PHPExcel library and sets the properties on the files
     */
    private function getPHPExcel()
    {
        // TODO: Load the excel library correctly
        require_once(dirname(__FILE__) . '/../../../../vendor/phpexcel/Classes//PHPExcel.php' );
        $phpExcel = new \PHPExcel();
        $now = new \DateTime();

        // Set the properties for the file
        $properties = $phpExcel->getProperties();
        $properties->setDescription("List of free online courses/MOOCs generated by Class Central");
        $properties->setCreator("Class Central - www.class-central.com");
        $properties->setTitle("List of free online courses/MOOCs generated by Class Central on " . $now->format("jS M, Y") );
        $properties->setSubject("List of free online courses/MOOCs generated by Class Central on " . $now->format("jS M, Y") );


        return $phpExcel;
    }

    private function setOfferingRow($activeSheet, $offering, $row)
    {
        $column = 0;
        $activeSheet->setCellValueByColumnAndRow($column++,$row,$offering['name']);

        $url = "https://www.class-central.com" . $this->getContainer()->get('router')->generate('ClassCentralSiteBundle_mooc', array('id' => $offering['courseId'],'slug' => $offering['courseSlug']));
        // Set a hyper link for the name column
        $link = new \PHPExcel_Cell_Hyperlink($url, $offering['name']);
        $activeSheet->setHyperlink('A'.$row, $link);

        $activeSheet->setCellValueByColumnAndRow($column++,$row, is_null($offering['length']) ? "NA" : $offering['length'] . ' weeks');
        $activeSheet->setCellValueByColumnAndRow($column++,$row, $offering['displayDate']);
        $activeSheet->setCellValueByColumnAndRow($column++,$row,$offering['stream']['name']);
        $activeSheet->setCellValueByColumnAndRow($column++,$row,$offering['initiative']['name']);

        //Institutions
        $institutions = array();
        foreach($offering['institutions'] as $institution)
        {
            $institutions[] = $institution['name'];
        }
        $activeSheet->setCellValueByColumnAndRow($column++,$row,implode(',',$institutions));

        //Instructors
        $activeSheet->setCellValueByColumnAndRow($column++,$row,implode(',',$offering['instructors']));
    }

}
