ClassCentral\SiteBundle\Entity\MoocTrackerCourse:
    type: entity
    table: mooc_tracker_courses
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        created:
            type: datetime
            nullable: true
    manyToOne:
        # many to one bidirectional
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: moocTrackerCourses
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        # many to one unidirectional
        course:
            targetEntity: Course
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                course_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
