ClassCentral\SiteBundle\Entity\Offering:
  type: entity
  repositoryClass: ClassCentral\SiteBundle\Repository\OfferingRepository
  table: offerings
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    startDate:
      type: date
      nullable: true
      column: start_date
    endDate:
      type: date
      nullable: true
      column: end_date
    shortName:
      type: string
      length: 255
      column: short_name
    exactDatesKnow:
      type: boolean
      nullable: true
      column: exact_dates_know
    created:
      type: datetime
      nullable: true
    modified:
      type: datetime
      nullable: false   
    url:
      type: text 
    videoIntro:
      type: text
      nullable: true
      column: video_intro  
    length:
      type: integer
      nullable: true
    name:
      type: string
      length: 255
      nullable: true
    status:
      type: integer
    searchDesc:
      type: text
      nullable: true
      column: search_desc
  manyToOne:
    course:
      targetEntity: Course
      fetch: EAGER
      cascade: {  }
      mappedBy: null
      inversedBy: offerings      
      orphanRemoval: false   
  manyToMany:
    instructors:
      targetEntity: Instructor
      inversedBy: offerings      
      joinTable: 
        name: offerings_instructors 
        joinColumns:
          offering_id:
            referencedColumnName: id
        inverseJoinColumns:
          instructor_id:
            referencedColumnName: id
      nullable: true      
  lifecycleCallbacks: {  }
