ClassCentral\SiteBundle\Entity\Spotlight:
    type: entity
    table: spotlights
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        position:
            type: integer
            unsigned: false
            nullable: false
        title:
            type: text
            nullable: false
        description:
            type: text
            nullable: false
        url:
            type: text
            nullable: false
        imageUrl:
            type: text
            nullable: false
            column: image_url
        type:
            type: integer
            unsigned: false
            nullable: false
    oneToOne:
        course:
            targetEntity: Course
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                course_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
