parameters:
#    class_central_site.example.class: ClassCentral\SiteBundle\Example

services:
#    class_central_site.example:
#        class: %class_central_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
